# Generated by Django 6.1 on 2026-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_specificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
