# Generated by Django 6.1 on 2026-09-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='products.usage'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.usage'),
        ),
    ]
